# Generated by Django 6.0.1 on 2026-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('disability_type', models.CharField(choices=[('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('speech', 'Speech Impairment'), ('motor', 'Motor Impairment'), ('cognitive', 'Cognitive Impairment'), ('general', 'General Accessibility')], max_length=20)),
                ('settings', models.JSONField(help_text='Preset accessibility settings as JSON')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accessibility Preset',
                'verbose_name_plural': 'Accessibility Presets',
                'db_table': 'accessibility_presets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuickPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('greeting', 'Greetings'), ('common', 'Common Responses'), ('emergency', 'Emergency'), ('emotion', 'Emotions'), ('question', 'Questions'), ('custom', 'Custom')], max_length=20)),
                ('phrase', models.TextField()),
                ('shortcut', models.CharField(blank=True, help_text='Keyboard shortcut or emoji trigger', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Phrase',
                'verbose_name_plural': 'Quick Phrases',
                'db_table': 'quick_phrases',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessibilityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('tts', 'Text-to-Speech'), ('stt', 'Speech-to-Text'), ('high_contrast', 'High Contrast Mode'), ('font_size', 'Font Size'), ('color_blind', 'Color Blind Mode'), ('haptic', 'Haptic Feedback'), ('navigation', 'Navigation'), ('other', 'Other')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accessibility Feedback',
                'verbose_name_plural': 'Accessibility Feedback',
                'db_table': 'accessibility_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
