# Generated by Django 6.0.1 on 2026-01-08 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessibility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickphrase',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system-wide phrases', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_phrases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccessibilityfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
