# Generated by Django 6.0.1 on 2026-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('music', 'Music'), ('white_noise', 'White Noise'), ('meditation', 'Meditation')], max_length=20)),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('description', models.TextField(blank=True)),
                ('recommended_moods', models.JSONField(default=list, help_text='List of mood types this sound is good for')),
                ('is_active', models.BooleanField(default=True)),
                ('play_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ambient Sound',
                'verbose_name_plural': 'Ambient Sounds',
                'db_table': 'ambient_sounds',
                'ordering': ['-play_count'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy 😄'), ('happy', 'Happy 🙂'), ('neutral', 'Neutral 😐'), ('sad', 'Sad 😢'), ('very_sad', 'Very Sad 😭'), ('anxious', 'Anxious 😰'), ('calm', 'Calm 😌'), ('energetic', 'Energetic ⚡'), ('tired', 'Tired 😴'), ('frustrated', 'Frustrated 😤'), ('grateful', 'Grateful 🙏')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'db_table': 'mood_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSoundSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_listened', models.IntegerField(default=0, help_text='Duration listened in seconds')),
                ('mood_before', models.CharField(blank=True, max_length=20)),
                ('mood_after', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Sound Session',
                'verbose_name_plural': 'Sound Sessions',
                'db_table': 'user_sound_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
